schema_version = "1.0.0"

id = "blender_for_unrealengine"
version = "4.3.1"
name = "Blender for UnrealEngine"
tagline = "Allows to batch export and import in Unreal Engine"
maintainer = "Loux Xavier (BleuRaven) xavierloux.loux@gmail.com"
type = "add-on"

website = "https://github.com/xavier150/Blender-For-UnrealEngine-Addons/"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "Copyright 2024, Xavier Loux. All rights reserved.",
]

platforms = ['windows-x64', 'linux-x64']

[permissions]
files = "Import/export FBX from/to disk"