schema_version = "1.0.0"

id = "blender_for_unrealengine"
version = "4.4.1"
name = "Blender for UnrealEngine with Remote Execution"
tagline = "Allows to batch export and import in Unreal Engine"
maintainer = "Loux Xavier (BleuRaven) xavierloux.loux@gmail.com + justOniL"
type = "add-on"

website = "https://github.com/justonil/BlenderForUERemoteExecution"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "Copyright 2024, Xavier Loux, justOniL. All rights reserved.",
]

platforms = ['windows-x64']

[permissions]
files = "Import/export FBX from/to disk"